# Project configuration

# Data settings
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  batch_size: 32
  num_workers: 4

# Model settings
model:
  name: "GraphSAGE"
  hidden_channels: 128
  num_layers: 3
  dropout: 0.2
  use_attention: true
  aggregation: "mean"  # Options: mean, max, sum, attention
  
  # Edge types (can be extended)
  edge_types:
    - "control_flow"
    - "data_flow"
    - "semantic"
  
  # Node feature settings
  node_features:
    embedding_dim: 20
    use_positional_encoding: true
    use_ast_type_features: true
    use_code_token_features: true
  
  # Pattern learning settings
  pattern_learning:
    num_patterns: 32
    pattern_dim: 64
    contrastive_margin: 0.5
    pattern_dropout: 0.1
    transformation_hidden_dim: 128

# Training settings
training:
  lr: 0.001
  weight_decay: 0.0001
  epochs: 100
  early_stopping_patience: 10
  scheduler_factor: 0.5
  scheduler_patience: 5
  save_dir: "models/saved_models"
  device: "cpu"  # Options: cuda, cpu
  gradient_clipping: 1.0
  loss_weights:
    classification: 1.0
    contrastive: 0.5
    reconstruction: 0.2

# Inference settings
inference:
  confidence_threshold: 0.7
  top_k_patterns: 5
  visualization_output: "results/visualizations"
  report_output: "results/reports"

# Extension settings
extensions:
  languages:
    - name: "cpp"
      enabled: true
      parser_path: "path/to/cpp/parser"
    - name: "python"
      enabled: false
      parser_path: "path/to/python/parser"
  
  vulnerability_types:
    - name: "buffer_overflow"
      enabled: true
    - name: "sql_injection"
      enabled: false
    - name: "use_after_free"
      enabled: true
    - name: "integer_overflow"
      enabled: true

# Logging settings
logging:
  level: "INFO"
  save_dir: "logs"
  use_tensorboard: true
  use_wandb: false
  wandb_project: "vulnerability-detection"
  log_frequency: 10  # Steps