version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/vulnerability_detection.log
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: error
    filename: logs/error.log
    encoding: utf8

loggers:
  # Module loggers
  src:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false
  
  src.data:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false
  
  src.models:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false
  
  src.inference:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false
  
  src.extensions:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler, error_file_handler]
  propagate: no